server:
  port: 8084

spring:
  application:
    name: pharmacy-service
  feign:
    hystrix:
      enabled: false
  cloud:
    loadbalancer:
      retry:
        enabled: true


  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
