spring:
  application:
    name: prescription-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
    port: 8083

rabbitmq:
  prescription:
    exchange: ${RABBITMQ_PRESCRIPTION_EXCHANGE}
    queue: ${RABBITMQ_PRESCRIPTION_QUEUE}
    routing-key: ${RABBITMQ_PRESCRIPTION_ROUTING_KEY}

logging:
  level:
    org.springframework: INFO
    com.management.prescriptionservice: DEBUG

tc:
  validation:
    url: ${TC_VALIDATION_URL}
