server:
  address: 127.0.0.1
  port: ${GATEWAY_PORT}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      routes:
        - id: auth_service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/$\{segment}
        - id: pharmacy_service
          uri: ${PHARMACY_SERVICE_URL}
          predicates:
            - Path=/api/pharmacies/**
          filters:
            - JwtCookieFilter
            - RewritePath=/api/pharmacies/(?<segment>.*), /api/pharmacies/$\{segment}
        - id: medicine_service
          uri: ${MEDICINE_SERVICE_URL}
          predicates:
            - Path=/api/medicines/v1/**
          filters:
            - RewritePath=/api/medicines/(?<segment>.*), /api/medicines/$\{segment}
        - id: prescription_service
          uri: ${PRESCRIPTION_SERVICE_URL}
          predicates:
              - Path=/api/prescriptions/**
          filters:
              - JwtCookieFilter
              - RewritePath=/api/prescriptions/(?<segment>.*), /api/prescriptions/$\{segment}

  frontend:
    url: ${FRONTEND_URL}

logging:
  level:
    org.springframework: debug