spring:
  application:
    name: medicine-service
  task:
    scheduling:
      pool:
        size: 10

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  address: 0.0.0.0
  port: 8082

logging:
  level:
    org.springframework: INFO